-full64 
-sverilog 
-timescale=1ns/1ps
+v2k 
-l compile.log
+incdir+${PROJECT_ROOT}/packages
+incdir+${PROJECT_ROOT}/cov_gen/common
+incdir+${PROJECT_ROOT}/cov_sample
+incdir+${PROJECT_ROOT}/autogen_samples
+incdir+${PROJECT_ROOT}/whisper
+incdir+${PROJECT_ROOT}/magic_enum/include/magic_enum

+libext+.v+.sv+.svh

# Include build directory for cp_pkg.sv 
${PROJECT_ROOT}/packages/cp_pkg.sv 

# Include common files 
${PROJECT_ROOT}/cov_sample/cov_common.sv 
${PROJECT_ROOT}/cov_sample/user_cov_common.sv 

# Include autogenerated sampling files 
${PROJECT_ROOT}/autogen_samples/attr_cov.sv 
${PROJECT_ROOT}/autogen_samples/enum_cov.sv 
${PROJECT_ROOT}/autogen_samples/csr_cov.sv 
${PROJECT_ROOT}/autogen_samples/instr_cov.sv 

# Include coverage files 
${PROJECT_ROOT}/covergroups/aext_cov.sv
#${PROJECT_ROOT}/covergroups/cext_cov.sv
#${PROJECT_ROOT}/covergroups/dext_cov.sv
#${PROJECT_ROOT}/covergroups/fext_cov.sv
#${PROJECT_ROOT}/covergroups/iext_cp.sv
#${PROJECT_ROOT}/covergroups/mext_cp.sv
#${PROJECT_ROOT}/covergroups/zfh_cov.sv

# Include user sampling files
${PROJECT_ROOT}/cov_sample/user_cov_sample.sv 
${PROJECT_ROOT}/cov_sample/arch_cov_sample.sv 

# Include top level TB files 
${PROJECT_ROOT}/cov_sample/cov_sample.sv 

# Include DPI files
${PROJECT_ROOT}/cov_sample/Sample.cpp
${PROJECT_ROOT}/cov_sample/cov_sample.cc

# Coverage options 
-cm_dir  ${PROJECT_ROOT}/coverage.vdb
-cm_name test_coverage