//  SPDX-FileCopyrightText: © 2026 Tenstorrent AI ULC
//  SPDX-License-Identifier: Apache-2.0
#pragma once

#include <iostream>
#include <map>
#include <fstream>
#include <string>
#include <vector>
#include <memory>
#include "Info.hpp"

using namespace ArchCov;

#define stringify(name) #name

template <typename URV>
class CovGen {
    private :
        //Handle to the ArchInfo class that collects data from whisper.
        Info<URV> arch_info;
        std::string filename;  
        typename Info<URV>::enumBins    enumsMap;
        typename Info<URV>::attBins     attsMap;
        typename Info<URV>::fieldsBins  fieldsMap;
        typename Info<URV>::csrBins     csrsMap;
        typename Info<URV>::instBins    instsMap;
        std::map<std::string, unsigned> archInfoPointsMap;

        //Vectors to organize strings to be printed into the SV Package.
        std::vector<std::string> enumStrings;
        std::vector<std::string> attributeStrings;
        std::vector<std::string> instStrings;
        std::vector<std::string> csrStrings;
        std::vector<std::string> globalVarStrings;
        std::vector<std::string> archInfoPoints;

        //Local variables/functions for sv file generation
        std::string header = "This is an autogenerated file";
        std::string padding = "-------------------------------------------------------";

        void printHeader(std::ofstream& CpFile);

        void printArchInfoPoints(std::ofstream& CpFile);

        void printEnums(std::ofstream& CpFile);

        void printAttributes(std::ofstream& CpFile);

        void printInstrs(std::ofstream& CpFile);

        void printCsrs(std::ofstream& CpFile);

        void printFooter(std::ofstream& CpFile);

        void add_constructor(CoverGroup cg,std::string& instrFmtAsString);

    public :

        //CovGen constructor : Accepts a HART object to be used for ArchInfo and a filename for SV package.
        CovGen(WdRiscv::Hart<URV>& hart,std::string filename);

        //Converts enum data collected from ArchInfo to equivalent SV declaration strings.
        void convertToEnumStrings();

        //Converts non-enum data (attributes and PTE/field decompositions) collected
        //from ArchInfo to equivalent SV declaration strings.
        void convertToAttributeStrings();

        //Generates SV declarations for all the coverpoints available.
        void convertToArchInfoPointStrings();

        //Generates SV declarations for all instruction fields.
        void convertToInstrStrings();

        //Generates SV declarations for all instruction fields.
        void convertToCsrStrings();

        //Wrapper function for extracting enums/attributes from ArchInfo.
        void extractArchInfo();

        //Generates SV package file.
        void generateCpPackage();

};

