#pragma once

#include <iostream>
#include <map>
#include <fstream>
#include <string>
#include <vector>
#include <memory>
#include "Info.hpp"

using namespace ArchCov;

#define stringify(name) #name

class Bin {
    public:

        Bin() {
           isArray = 0;
           isSpecialBin = 0;
           arrSize = "";
        }

        bool isArray;
        bool isSpecialBin;

        std::string arrSize;
        std::string name;
        std::string vals;
        std::string content;

};

class CoverPoint {
    public:
        std::string name;
        std::vector<Bin> bins;
        bool isEnum;
};

class CoverGroup {
    public:
        std::string name;
        std::vector<std::pair<std::string,std::string>> bitmasks;
        std::string qualifier;
        std::vector<std::string> inputs;
        std::vector<CoverPoint>  cps;
};

template <typename URV>
class CovGen {
    private :
        //Handle to the ArchInfo class that collects data from whisper.
        Info<URV> arch_info;
        std::string filename;  
        typename Info<URV>::enumBins    enumsMap;
        typename Info<URV>::attBins     attsMap;
        typename Info<URV>::fieldsBins  fieldsMap;
        typename Info<URV>::csrBins     csrsMap;
        typename Info<URV>::instBins    instsMap;
        std::map<std::string, unsigned> archInfoPointsMap;

        //Vectors to organize strings to be printed into the SV Package.
        std::vector<std::string> enumStrings;
        std::vector<std::string> attributeStrings;
        std::vector<std::string> instStrings;
        std::vector<std::string> csrStrings;
        std::vector<std::string> globalVarStrings;
        std::vector<std::string> archInfoPoints;

        //Local variables/functions for sv file generation
        std::string header = "This is an autogenerated file";
        std::string padding = "-------------------------------------------------------";

        void printHeader(std::ofstream& CpFile);

        void printArchInfoPoints(std::ofstream& CpFile);

        void printEnums(std::ofstream& CpFile);

        void printAttributes(std::ofstream& CpFile);

        void printInstrs(std::ofstream& CpFile);

        void printCsrs(std::ofstream& CpFile);

        void printFooter(std::ofstream& CpFile);

        //void gen_attribute(std::string attrName, Attribute attrVal, std::string& attrAsString);

        //void gen_enum(std::string enumName, enum_val_t enumVal, std::string& enumAsString);

        void create_bin(Bin bin, std::string& binAsString);

        void create_coverpoint(CoverPoint cp, bool isCsr, std::string qualifier, std::string& cpAsString);

        void create_covergroup(CoverGroup cg, bool isCsr, std::string& cgAsString);

        void create_class(CoverGroup cg, bool isCsr, std::vector<std::string> operands, std::string& classAsString);

        void add_constructor(CoverGroup cg,std::string& instrFmtAsString);

    public :
              std::map<std::string,std::vector<std::string>> IMAExtCategoryMap {
        {"CSR_INSTRS", {"csrrc","csrrci","csrrs","csrrsi","csrrw","csrrwi"}},
    
        {"ARITHMETIC_INSTRS",{"add","addi","addiw","addw","and","andi","auipc","lui", 
                              "or","ori","sll","slli","slliw","sllw","slt","slti","sltiu",
                              "sltu","sra","srai","sraiw","sraw","srl","srli","srliw","srlw",
                              "sub","subw","xor","xori"}},
        {"MUL_INSTRS", {"mul", "mulh", "mulhsu", "mulw"}},
        {"DIV_INSTRS", {"div", "divu", "divuw", "divw"}},
        {"REM_INSTRS", {"rem", "remu", "remuw", "remw"}},

        {"CONDITIONAL_BRANCH_INSTRS", {"beq","bge","bgeu","blt","bltu","bne"}},

        {"DEBUG_INSTRS", {"dret","ebreak","wfi"}},
    
        {"SYSTEM_INSTRS", {"ecall","mret","sret"}},    

        {"SYNCH_INSTRS", {"fence","fence_i","fence_tso"}},

        {"ILLEGAL_INSTRS", {"illegal"}},
    
        {"UNCONDITIONAL_BRANCH_INSTRS", {"jal""jalr"}},
    
        {"LOAD_INSTRS",  {"lb","lbu","ld","lh","lhu","lw","lwu"}},

        {"STORE_INSTRS", {"sb","sh","sw","sd"}},

        {"AMO_INSTRS", {"amoswap_w","amoadd_w","amoxor_w",
                        "amoand_w","amoor_w","amomin_w",
                        "amomax_w","amominu_w","amomaxu_w",
                        "amoswap_d","amoadd_d","amoxor_d",
                        "amoand_d","amoor_d","amomin_d"}},

        {"LR_SC_INSTRS", {"lr_w","sc_w","lr_d","sc_d"}}
    };

        //CovGen constructor : Accepts a HART object to be used for ArchInfo and a filename for SV package.
        CovGen(WdRiscv::Hart<URV>& hart,std::string filename);

        //Converts enum data collected from ArchInfo to equivalent SV declaration strings.
        void convertToEnumStrings();

        //Converts non-enum data collected from ArchInfo to equivalent SV declaration strings.
        void convertToAttributeStrings();

        //Generates SV declarations for all the coverpoints available.
        void convertToArchInfoPointStrings();

        //Generates SV declarations for all instruction fields.
        void convertToInstrStrings();

        //Generates SV declarations for all instruction fields.
        void convertToCsrStrings();

        //Wrapper function for extracting enums/attributes from ArchInfo.
        void extractArchInfo();

        //Generates SV package file.
        void generateCpPackage();

};

