import sys
import os
import re
from collections import defaultdict
import argparse

invalid = []

def generate_attrs_file(filename,fileContent):
    lines = []
    lines += generate_header(filename)
    lines.append(f'\tfunction void sample(input cp_table table);\n')
    for enumName, enumVal in fileContent.items():
        lines += enumVal.sample()
    lines.append(f'\tendfunction')
    lines += generate_footer()
    with open (f'{filename}','w') as outputFile:
        for line in lines:
            outputFile.write(line+"\n")

def generate_enums_file(filename,fileContent):
    lines = []
    lines += generate_header(filename)
    lines.append(f'\tfunction void sample(input cp_table table);\n')
    for enumName, enumVal in fileContent.items():
        lines += enumVal.sample()
    lines.append(f'\tendfunction')
    lines += generate_footer()
    with open (f'{filename}','w') as outputFile:
        for line in lines:
            outputFile.write(line+"\n")


def generate_file(filename,fileContent,isCsr) :
    lines = generate_header(filename) + generate_body(fileContent,isCsr) + generate_footer()
    with open(f'{filename}','w') as outputFile:
        for line in lines:
            outputFile.write(line)

def generate_header(filename):
    header = []
    defineName = filename.replace('.','_').replace('-', '_').replace('/', '_').upper()
    className  = filename.split('/')[-1].split('.')[0]
    header.append(f'/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT MANUALLY */\n\n')
    header.append(f'`ifndef {defineName}\n')
    header.append(f'`define {defineName}\n')
    header.append(f'`ifndef COVERAGE_UNSUPPORTED\n')

    header.append(f'import cov_common::*;\n\n')
    header.append(f'import user_cov_common::*;\n\n')
    header.append(f'import cp_pkg::*;\n\n')
    header.append(f'class {className};\n\n')
    return header

def generate_footer():
    footer = []
    footer.append(f'endclass\n')
    footer.append(f'`endif\n')
    footer.append(f'`endif')
    return footer

def generate_body(fileContent,isCsr):
    body                = []
    sample_calls        = []
    class_decl          = []
    covergroup_new      = []

    global_inputs = set()
    global_inputs_as_string = ""

    covergroup_new.append('\tfunction new();\n\n')
    for _,val in fileContent.items():
        if val.isValid:
            class_decl.append(val.declare())
            covergroup_new.append(val.instantiate())
            sample_calls.append(val.sample())
            val.generate_global_inputs(global_inputs)
        else:
            invalid.append(val.name)

    global_inputs_as_string =  '\n\t\t'.join(sorted(global_inputs))

    covergroup_new.append(f'\tendfunction\n\n')
    class_decl.append("\n")

    body = class_decl + covergroup_new
    if isCsr:
        sampleFunctionName = "sample_sv_csr"
    else:
        sampleFunctionName = "sample_sv_instr"

    body.append(f'\tfunction void {sampleFunctionName}(input cp_table table);\n\n')
    body.append(f'\t\t{global_inputs_as_string}\n\n')

    if isCsr:
        pass
    else:
        body.append(f'\t\tif(table.exists(POINT_INSTID)) begin\n \t\t\t $cast(instrenum_var, table.get_cp_val(POINT_INSTID));\n\t\tend\n\n')
        for op in ["OP0","OP1","OP2","OP3","OP0VAL","OP1VAL","OP2VAL","OP3VAL"]:
            body.append(f'\t\tif(table.exists(POINT_{op})) begin\n \t\t\t {op.title()} = table.get_cp_val(POINT_{op});\n\t\tend\n\n')

    body = body + sample_calls

    body.append(f'\tendfunction\n\n')
    return body

class coverGroup:

    def __init__(self,cgName,cgInputs):
        self.name   = cgName
        self.args   = cgInputs

    def get_arg_names_only(self):
        inputs = []
        for arg in self.args:
            inputs.append(arg.split(" ")[-1])
        return inputs

class InstrCsrBase:

    def __init__(self,className):
        self.name        = className
        self.covergroups = []
        self.isValid     = False

    def parse(self,classContent):
        for line in classContent:
            matches = re.findall(r'covergroup (.*) with function sample \((.*)\);',line)
            if len(matches):
                cgName    = matches[0][0].strip()
                operands  = list(filter(None,matches[0][1].strip().split(',')))
                if(len(operands)):
                    cg        = coverGroup(cgName,operands)
                    self.covergroups.append(cg)
                    self.isValid = True
                else:
                    self.isValid = False

    def get_args(self):
        args = []
        for cg in self.covergroups:
            args += cg.args

        return args

    def get_arg_names_only(self):
        args = []
        for cg in self.covergroups:
            args += cg.get_arg_names_only()

        return args

class instrClass(InstrCsrBase):

    def __init__(self, className):
        super().__init__(className)
        self.members = [] 

    def declare(self):
        return f'\t{self.name} {self.name}_inst;\n'

    def instantiate(self):
        return f'\t\t{self.name}_inst = new();\n'

    def sample(self):
        samples = []

        for cg in self.covergroups:
            inputs_as_string = ','.join(self.get_arg_names_only())
            samples.append(f'\t\t{self.name}_inst.{cg.name}.sample({inputs_as_string});\n')

        sampleAsString = ''.join(samples)
        return sampleAsString

    def generate_global_inputs(self,global_inputs):
        global_inputs.add(f'csr_Op2_e       csr_op2_var;')
        global_inputs.add(f'fext_Rm_e       fext_rm_var;')
        global_inputs.add(f'logic BrTaken;')
        global_inputs.add("logic[63:0]\tOp0,Op1,Op2,Op3;")
        global_inputs.add("logic[63:0]\tOp0Val,Op1Val,Op2Val,Op3Val;")

class csrClass(InstrCsrBase):

    def __init__(self, className):
        super().__init__(className)
        self.members = [] 

    def declare(self):
        return f'\t{self.name} {self.name}_inst;\n'

    def instantiate(self):
        return f'\t\t{self.name}_inst = new();\n'

    def sample(self):
        samples = []
        csrEnum = "CSRENUM_"+self.name.upper()[:-4]
        # print(csrEnum)
        for cg in self.covergroups:
            formatted_args = []
            for arg in cg.get_arg_names_only():
                formatted_args.append(f'{self.name}_{arg}')
            inputs_as_string = ','.join(formatted_args)
            samples.append(f'\t\tcsr = table.get_csr(cp_pkg::{csrEnum});\n')
            samples.append(f'\t\tif(csr != null) begin\n')
            samples.append(f'\t\t\tcsrenum_var = csr.name;\n')
            samples.append(f'\t\t\tCsrVal = csr.value;\n')
            samples.append(f'\t\t\t{self.name}_inst.bit_slice_csr_fields(CsrVal);\n')
            for arg in self.members:
                arg_name = arg['name'] if isinstance(arg, dict) else arg
                if arg_name != 'value':
                    samples.append(f'\t\t\t{self.name}_{arg_name} = {self.name}_inst.{arg_name};\n')
            samples.append(f'\t\t\t{self.name}_inst.{cg.name}.sample({inputs_as_string});\n\n')
            samples.append(f'\t\tend\n')

        sampleAsString = ''.join(samples)
        return sampleAsString

    def generate_global_inputs(self,global_inputs):
        #print(len(self.members))
        for m in self.members:
            name = m['name'] if isinstance(m, dict) else m
            #print(f'name: {name}')
            bitwidth = m.get('bitwidth', '') if isinstance(m, dict) else ''
            #print(f'bitwidth: {bitwidth}')
            if bitwidth:
                global_inputs.add(f'logic {bitwidth} {self.name}_{name};')
            else:
                global_inputs.add(f'logic {self.name}_{name};')

        global_inputs.add("csrType\tcsr;")
        global_inputs.add("logic[63:0]\tCsrVal;")
        #global_inputs.add("logic[63:0]\tmaskedVal;")
    
class svEnumClass:

    def __init__(self,name,content):
        self.name   = name
        self.values = []
        for value in content: 
            self.values.append(value.replace(",",""))
        
    def sample(self):
        samples = []
        enum_name = self.name[:-2].lower()
        if self.name not in ['csrEnum_e','csr_Op2_e','fext_Rm_e'] : 
            if self.name in ['instrEnum_e'] or self.name.endswith('Ext_e') or self.name.endswith('Format_e') or self.name.endswith('_instrs_e') or self.name.startswith('rvv'):
                archPointName = 'POINT_INSTID'
            elif self.name.startswith("csrs"):
                archPointName = f'POINT_CSRNUM'
            else:
                archPointName = f'POINT_{enum_name.upper()}'
            samples.append(f'\t\tif(table.exists({archPointName})) begin')
            samples.append(f'\t\t\t{enum_name}_var = {self.name}\'(table.get_cp_val({archPointName}));')
            samples.append(f'\t\tend\n')
        elif self.name == 'fext_Rm_e':
            archPointName ='POINT_RM'
            samples.append(f'\t\tif(table.exists({archPointName})) begin')
            samples.append(f'\t\t\t{enum_name}_var = {self.name}\'(table.get_cp_val({archPointName}));')
            samples.append(f'\t\tend\n')

        return samples

class svAttrClass: 

    def __init__(self,name,size=""):
        self.name = name 
        self.size = size
    
    def sample(self):
        samples = []
        archPointName  = f'POINT_{self.name.upper()}'
        samples.append(f'\t\tif(table.exists(cp_pkg::{archPointName})) begin')
        samples.append(f'\t\t\t{self.name} = table.get_cp_val(cp_pkg::{archPointName});')
        samples.append(f'\t\tend\n')
        return samples
        
def parse_attr(attrContent):
    attrs = defaultdict(svAttrClass)
    pattern = r'logic\s+(?:\[(\d+):(\d+)\]\s+)?(\w+);'
    for line in attrContent:
        match = re.findall(pattern,line)
        if len(match) != 0:
            attrName = match[0][-1]
            attr = svAttrClass(attrName)
            attrs[attrName] = attr
    return attrs 

def parse_enums(enumContent):
    enums = defaultdict(svEnumClass)
    extract = False
    content = []

    for line in enumContent:

        enumStartMatch = re.findall(r'typedef enum',line)
        enumEndMatch   = re.findall(r"} (\w+)",line)
        if len(enumStartMatch):
            extract = True
            continue
        elif len(enumEndMatch):
            enumName = enumEndMatch[0]
            svEnum   = svEnumClass(enumName,content)
            enums[enumName] = svEnum
            extract = False
            content = []
            continue
        elif extract: 
            if line != "\n":
                content.append(line) 
    return enums

def parse_csrs(csrContent):
    """Parse CSR section from cp_pkg.sv. Extract from each class (name ends with _csr):
    1. class name
    2. covergroup name
    3. class members (names after 'logic')
    4. inputs to covergroup (string inside sample function of covergroup)
    """
    csrs = defaultdict(csrClass)
    i = 0
    lines = list(csrContent)

    while i < len(lines):
        line = lines[i]
        class_match = re.search(r'class\s+(\w+_csr)\s*;', line)
        if class_match:
            class_name = class_match.group(1).strip()
            start = i
            i += 1
            while i < len(lines):
                if re.search(r'endclass\s*:\s*' + re.escape(class_name), lines[i]):
                    block = lines[start : i + 1]
                    csr_obj = _parse_one_csr_class(class_name, block)
                    if csr_obj is not None:
                        csrs[class_name] = csr_obj
                    i += 1
                    break
                i += 1
            continue
        i += 1
    return csrs


def _parse_one_csr_class(class_name, block):
    """Parse a single CSR class block. Returns csrClass or None."""
    members = []
    covergroup_name = None
    sample_inputs = []  # list of "logic XX" or "logic [n:m] XX" strings
    in_function = False

    for line in block:
        # 1. Class name already known (passed in).

        # 2 & 4. covergroup name and sample inputs
        cg_match = re.search(r'covergroup\s+(\w+)\s+with\s+function\s+sample\s*\((.*)\)\s*;', line)
        if cg_match:
            covergroup_name = cg_match.group(1).strip()
            args_str = cg_match.group(2).strip()
            # Split by comma and strip; each part is e.g. "logic DZ" or "logic [2:0] frm"
            sample_inputs = [part.strip() for part in re.split(r'\s*,\s*', args_str) if part.strip()]

        # 3. class members (logic declarations before first function); preserve bitwidth
        if re.search(r'\bfunction\b', line):
            in_function = True
        if not in_function:
            # logic [63:0] value; or logic value; or logic NX ; or logic [2:0] frm ;
            # Capture optional bitwidth and signal name (single-bit has no bitwidth)
            mem_match = re.search(r'^\s*logic\s*(\[\d+:\d+\])?\s*(\w+)\s*;', line)
            if mem_match:
                bitwidth = mem_match.group(1) or ''   # '' for single-bit
                name = mem_match.group(2)
                members.append({'name': name, 'bitwidth': bitwidth})

    if covergroup_name is None or not sample_inputs:
        return None

    csr_obj = csrClass(class_name)
    csr_obj.covergroups = [coverGroup(covergroup_name, sample_inputs)]
    csr_obj.members = members
    csr_obj.isValid = True

    return csr_obj

def parse_instrs(instrContent):
    instrs = defaultdict(instrClass)
    i = 0
    lines = list(instrContent)
    while i < len(lines):
        line = lines[i]
        class_match = re.search(r'class\s+(\w+_instr)\s*;', line)
        if class_match:
            class_name = class_match.group(1).strip()
            start = i
            i += 1
            while i < len(lines):
                if re.search(r'endclass\s*:\s*' + re.escape(class_name), lines[i]):
                    block = lines[start : i + 1]
                    instr_obj = _parse_one_instr_class(class_name, block)
                    if instr_obj is not None:
                        instrs[class_name] = instr_obj
                    i += 1
                    break
                i += 1
            continue
        i += 1
    return instrs 

def _parse_one_instr_class(class_name, block):
    """Parse a single instruction class block. Returns instrClass or None."""
    members = []
    covergroup_name = None
    sample_inputs = []  # list of "logic XX" or "logic [n:m] XX" strings
    in_function = False

    for line in block:

        cg_match = re.search(r'covergroup\s+(\w+)\s+with\s+function\s+sample\s*\((.*)\)\s*;', line)
        if cg_match:
            covergroup_name = cg_match.group(1).strip()
            args_str = cg_match.group(2).strip()
            sample_inputs = [part.strip() for part in re.split(r'\s*,\s*', args_str) if part.strip()]

        if re.search(r'\bfunction\b', line):
            in_function = True
        if not in_function:
            mem_match = re.search(r'^\s*logic\s*(\[\d+:\d+\])?\s*(\w+)\s*;', line)
            if mem_match:
                bitwidth = mem_match.group(1) or ''   # '' for single-bit
                name = mem_match.group(2)
                members.append({'name': name, 'bitwidth': bitwidth})
        
    if covergroup_name is None or not sample_inputs:
        return None

    instr_obj = instrClass(class_name)
    instr_obj.covergroups = [coverGroup(covergroup_name, sample_inputs)]
    instr_obj.members = members
    instr_obj.isValid = True

    return instr_obj

def parse_cp_pkg(cp_pkg_path):

    enums = defaultdict(svEnumClass)
    attrs = defaultdict(svAttrClass)
    csrs = defaultdict(csrClass)
    instrs = defaultdict(instrClass)

    with open(cp_pkg_path) as cp_pkg:
        
        extractEnum = False
        enum_content = []
        
        extractAttr = False
        attr_content = []
        
        extractCsr = False
        csr_content = []
        
        extractInstr = False
        instr_content = []
        
        for line in cp_pkg:
            enum_section_start = re.findall(r'Enums {',line)
            attr_section_start = re.findall(r'Attributes {',line)
            csr_section_start  = re.findall(r'Csrs {',line)
            instr_section_start = re.findall(r'Instrs {',line)

            if len(enum_section_start):
                extractEnum = True
                print(f'Found enum section')
                continue
            
            elif len(attr_section_start):
                extractAttr = True
                print(f'Found attr section')
                continue
            
            elif len(csr_section_start):
                extractCsr = True
                print(f'Found csr section')
                continue

            elif len(instr_section_start):
                extractInstr = True
                print(f'Found instr section')
                continue

            if extractEnum and len(re.findall(r'//}',line)):
                print(f'Found end of enum section')
                extractEnum = False
                enums = parse_enums(enum_content)
                enum_content = []
                continue
            elif extractAttr and len(re.findall(r'//}',line)):
                print(f'Found end of attr section')
                extractAttr = False
                attrs = parse_attr(attr_content)
                attr_content = []
                continue
            elif extractCsr and len(re.findall(r'//}',line)):
                print(f'Found end of csr section')
                extractCsr = False
                csrs = parse_csrs(csr_content)
                csr_content = []
                continue
            elif extractInstr and len(re.findall(r'//}',line)):
                print(f'Found end of instr section')
                extractInstr = False
                instrs = parse_instrs(instr_content)
                instr_content = []
                continue

            if extractEnum and line != "\n":
                enum_content.append(line)
            elif extractAttr and line != "\n":
                attr_content.append(line)
            elif extractCsr and line != "\n":
                csr_content.append(line)
            elif extractInstr and line != "\n":
                instr_content.append(line)

    return enums, attrs, csrs, instrs
        
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Script for generating sampling SV code')
    parser.add_argument('--cp_pkg', type=str, default='.', help='path to cp_pkg (default: current directory)')
    args = parser.parse_args()

    # Resolve cp_pkg: if directory or '.', use default filename in that directory
    cp_pkg_path = args.cp_pkg
    if cp_pkg_path == '.' or os.path.isdir(cp_pkg_path):
        cp_pkg_path = os.path.join(cp_pkg_path, 'cp_pkg.sv')

    # Create output directory and set paths for the 4 coverage output files
    output_dir = 'autogen_samples'
    os.makedirs(output_dir, exist_ok=True)
    instr_cov_filename  = os.path.join(output_dir, 'instr_cov.sv')
    csr_cov_filename    = os.path.join(output_dir, 'csr_cov.sv')
    enums_cov_filename  = os.path.join(output_dir, 'enums_cov.sv')
    attr_cov_filename   = os.path.join(output_dir, 'attr_cov.sv')

    instrs              = defaultdict(instrClass)
    csrs                = defaultdict(csrClass)
    enums               = defaultdict(svEnumClass)
    attrs               = defaultdict(svAttrClass)

    enums, attrs, csrs, instrs = parse_cp_pkg(cp_pkg_path)
    
    generate_file(instr_cov_filename,instrs,0)
    generate_file(csr_cov_filename,csrs,1)
    generate_enums_file(enums_cov_filename,enums)
    generate_attrs_file(attr_cov_filename,attrs)

